# See: https://docs.docker.com/compose/multiple-compose-files/merge/
services:
  reverse-proxy:
    environment:
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO: "websecure"
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: "https"
    volumes:
      - letsencrypt:/letsencrypt

  frontend:
    restart: always
    build:
      target: production

  backend:
    restart: always
    build:
      target: production
    environment:
      APP_OPENAPI_SWAGGER_UI_CONFIG: '{ "url": "https://${APP_DOMAIN_NAME:?}/api/specification.json" }'

  database:
    restart: always
    volumes:
      - data-db:/data/db

secrets:
  database_password:
    file: secrets/app_database_password

volumes:
  letsencrypt:
  data-db:
