# See: https://docs.docker.com/compose/multiple-compose-files/merge/
services:
  testing:
    restart: no
    build:
      dockerfile: Dockerfile.test
    depends_on:
      reverse-proxy:
        condition: service_healthy
    network_mode: "host"
    environment:
      APP_DOMAIN_NAME: ${APP_DOMAIN_NAME:?}
      DRIFT_MONITOR_DOMAIN: ${DRIFT_MONITOR_DOMAIN:?}
      DRIFT_MONITOR_MYTOKEN: ${DRIFT_MONITOR_MYTOKEN:?}
      TESTING: "true"

  reverse-proxy:
    restart: no
    environment:
      TRAEFIK_CERTIFICATESRESOLVERS_RESOLVER0_ACME_CASERVER: "https://acme-staging-v02.api.letsencrypt.org/directory"
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO: "websecure"
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: "https"

  frontend:
    restart: no
    build:
      target: production

  backend:
    restart: no
    build:
      target: production
    environment:
      APP_OPENAPI_SWAGGER_UI_CONFIG: '{ "url": "https://${APP_DOMAIN_NAME:?}/api/specification.json" }'
      APP_DATABASE_NAME: test-data

  database:
    restart: no
    volumes:
      - ./sandbox/load-database.sh:/docker-entrypoint-initdb.d/load-db.sh:ro
      - ./sandbox/database:/tmp/database
    environment:
      MONGO_INITDB_DATABASE: test-data

secrets:
  database_password:
    file: sandbox/secrets/app_database_password
