# See: https://docs.docker.com/compose/multiple-compose-files/merge/
services:
  reverse-proxy:
    volumes:
      - ./letsencrypt:/letsencrypt

  frontend:
    restart: always
    build:
      target: production

  backend:
    restart: always
    build:
      target: production

  database:
    restart: always
    volumes:
      - data-db:/data/db

secrets:
  database_password:
    file: secrets/app_database_password

volumes:
  data-db:
