# See: https://docs.docker.com/compose/multiple-compose-files/merge/
services:
  reverse-proxy:
    restart: unless-stopped
    environment:
      TRAEFIK_LOG_LEVEL: "DEBUG"
      TRAEFIK_CERTIFICATESRESOLVERS_RESOLVER0_ACME_CASERVER: "https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "8082:8082"
    volumes:
      - ./letsencrypt:/letsencrypt

  swagger-ui:
    image: swaggerapi/swagger-ui:${APP_SWAGGER_UI_VERSION-v5.17.3}
    environment:
      URLS: >
        [
         {"name": "HTTPS-latest", "url": "https://${APP_DOMAIN_NAME:?}/api/latest/specification.json"}, 
         {"name": "HTTPS-v1", "url": "https://${APP_DOMAIN_NAME:?}/api/v1/specification.json"}
        ]
    depends_on:
      - reverse-proxy

  frontend:
    restart: unless-stopped
    build:
      target: development
    environment:
      DRIFT_MONITOR_SCHEME: http
      DRIFT_MONITOR_HOST: backend-latest
      DRIFT_MONITOR_PORT: 5000
    ports:
      - "8501:8501"
      - "5679:5678"
    volumes:
      - ./frontend:/srv

  backend-latest:
    restart: unless-stopped
    build:
      target: development
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - ./backend/app:/srv/app
    environment:
      FLASK_DEBUG: 1
      APP_DATABASE_NAME: test-data

  backend-v1:
    restart: unless-stopped
    build:
      target: production
    ports:
      - "5001:5000"
    volumes:
      - ./backend/app:/srv/app
    environment:
      FLASK_DEBUG: 1
      APP_DATABASE_NAME: test-data

  database:
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./sandbox/load-database.sh:/docker-entrypoint-initdb.d/load-db.sh:ro
      - ./sandbox/database:/tmp/database
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: test-data

secrets:
  database_password:
    file: sandbox/secrets/app_database_password
