# See: https://docs.docker.com/compose/multiple-compose-files/merge/
version: "3.8"

services:
  reverse-proxy:
    restart: unless-stopped
    environment:
      TRAEFIK_LOG_LEVEL: "DEBUG"
    # secrets:
    #   - source: tls_certificate_key
    #     target: localhost.key
    ports:
      - "8082:8082"
    volumes:
      - ./sandbox/certificates/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./sandbox/certificates/localhost.key:/etc/ssl/certs/localhost.key:ro

  frontend:
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/srv

  backend:
    restart: unless-stopped
    build:
      target: development
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - ./backend/app:/srv/app
    environment:
      FLASK_DEBUG: 1
      APP_DATABASE_NAME: test-data

  database:
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./sandbox/load-database.sh:/docker-entrypoint-initdb.d/load-db.sh:ro
      - ./sandbox/database:/tmp/database
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: test-data

secrets:
  database_password:
    file: sandbox/secrets/app_database_password
  # tls_certificate_key:
  #   file: sandbox/certificates/localhost.key
