# See: https://docs.docker.com/compose/multiple-compose-files/merge/
services:
  reverse-proxy:
    image: traefik:${APP_TRAEFIK_VERSION-v3.2}
    environment:
      DOMAIN_NAME: ${APP_DOMAIN_NAME:?}
      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: ":80"
      TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: ":443"
      TRAEFIK_ENTRYPOINTS_PING_ADDRESS: ":8082"
      TRAEFIK_PROVIDERS_FILE_DIRECTORY: "/etc/traefik"
      TRAEFIK_PING_ENTRYPOINT: "ping"
      TRAEFIK_ACCESSLOG: "true"
      TRAEFIK_CERTIFICATESRESOLVERS_RESOLVER0_ACME_HTTPCHALLENGE: "true"
      TRAEFIK_CERTIFICATESRESOLVERS_RESOLVER0_ACME_HTTPCHALLENGE_ENTRYPOINT: "web"
      TRAEFIK_CERTIFICATESRESOLVERS_RESOLVER0_ACME_EMAIL: ${APP_LETSENCRYPT_EMAIL:?}
      TRAEFIK_CERTIFICATESRESOLVERS_RESOLVER0_ACME_STORAGE: "/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./reverse-proxy:/etc/traefik

  swagger-ui:
    image: swaggerapi/swagger-ui:${APP_SWAGGER_UI_VERSION-v5.17.3}
    depends_on:
      - reverse-proxy
      - backend-latest
      - backend-v1

  frontend:
    build:
      context: frontend
    depends_on:
      - backend-latest

  backend-latest:
    environment:
      APP_API_SPEC_OPTIONS: '{ "servers": [{"url": "/api/latest"}] }'
      APP_API_VERSION: latest
      APP_DATABASE_USERNAME: ${APP_DATABASE_USERNAME:-user-default}
      APP_DATABASE_HOST: database
      APP_SECRETS_DIR: /run/secrets
      APP_ADMIN_ENTITLEMENTS: ${APP_ADMIN_ENTITLEMENTS:?}
      APP_TRUSTED_OP_LIST: ${APP_TRUSTED_OP_LIST:?}
    build:
      context: backend
    depends_on:
      - database
    secrets:
      - source: database_password
        target: app_database_password

  backend-v1:
    environment:
      APP_API_SPEC_OPTIONS: '{ "servers": [{"url": "/api/v1"}] }'
      APP_API_VERSION: v1
      APP_DATABASE_USERNAME: ${APP_DATABASE_USERNAME:-user-default}
      APP_DATABASE_HOST: database
      APP_SECRETS_DIR: /run/secrets
      APP_ADMIN_ENTITLEMENTS: ${APP_ADMIN_ENTITLEMENTS:?}
      APP_TRUSTED_OP_LIST: ${APP_TRUSTED_OP_LIST:?}
    build:
      context: backend # Change to backend_v1 submodule with v~=1
    depends_on:
      - database
    secrets:
      - source: database_password
        target: app_database_password

  database:
    image: mongo:${APP_DATABASE_VERSION-8.0}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${APP_DATABASE_USERNAME:-user-default}
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/password
    secrets:
      - source: database_password
        target: password
