# See: https://docs.docker.com/compose/multiple-compose-files/merge/
version: "3.8"

services:
  frontend:
    restart: no
    build:
      target: production

  backend:
    restart: no
    build:
      target: production
    environment:
      APP_DATABASE_NAME: test-data

  testing:
    restart: no
    build:
      context: tests
    depends_on:
      # - frontend
      - backend
    environment:
      DRIFT_MONITOR_URL: http://backend:8000

  database:
    restart: no
    volumes:
      - ./sandbox/db-load.sh:/docker-entrypoint-initdb.d/db-load.sh:ro
      - ./sandbox/database:/tmp/database
    environment:
      MONGO_INITDB_DATABASE: test-data

secrets:
  database_password:
    file: sandbox/secrets/app_database_password
