# See: https://docs.docker.com/compose/multiple-compose-files/merge/
version: "3.8"

services:
  testing:
    restart: no
    build:
      context: tests
    depends_on:
      reverse-proxy:
        condition: service_healthy
    network_mode: "host"
    environment:
      TEST_BACKEND_ADDRESS: localhost

  reverse-proxy:
    restart: no
    healthcheck:
      test: "traefik healthcheck"
      start_period: 2s
      interval: 2s

  frontend:
    restart: no
    build:
      target: production

  backend:
    restart: no
    build:
      target: production
    environment:
      APP_DATABASE_NAME: test-data

  database:
    restart: no
    volumes:
      - ./sandbox/db-load.sh:/docker-entrypoint-initdb.d/db-load.sh:ro
      - ./sandbox/database:/tmp/database
    environment:
      MONGO_INITDB_DATABASE: test-data

secrets:
  database_password:
    file: sandbox/secrets/app_database_password
