# See: https://docs.docker.com/compose/multiple-compose-files/merge/
services:
  reverse-proxy:
    environment:
      CORS_ORIGINS: "https://${APP_DOMAIN_NAME}, http://localhost:3001"
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO: "websecure"
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: "https"
    volumes:
      - letsencrypt:/letsencrypt
    healthcheck:
      test: "traefik healthcheck"
      start_interval: 1s
      start_period: 10s

  swagger-ui:
    environment:
      URLS: >
        [
         {"name": "HTTPS-latest", "url": "https://${APP_DOMAIN_NAME:?}/api/latest/specification.json"}, 
         {"name": "HTTPS-v1", "url": "https://${APP_DOMAIN_NAME:?}/api/v1/specification.json"}
        ]
    depends_on:
      reverse-proxy:
        condition: service_healthy

  backend-latest:
    restart: always
    environment:
      APP_DATABASE_NAME: ${APP_DATABASE_NAME:-demo-data}
    build:
      target: production
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: "curl -X GET --fail localhost:5000"
      start_interval: 1s
      start_period: 10s

  backend-v1:
    restart: always
    environment:
      APP_DATABASE_NAME: ${APP_DATABASE_NAME:-demo-data}
    build:
      target: production
    depends_on:
      database:
        condition: service_healthy
    secrets:
      - source: database_password
        target: app_database_password
    healthcheck:
      test: "curl -X GET --fail localhost:5000"
      start_interval: 1s
      start_period: 10s

  database:
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${APP_DATABASE_NAME:-demo-data}
    volumes:
      - ./sandbox/load-database.sh:/docker-entrypoint-initdb.d/load-db.sh:ro
      - ./sandbox/database:/tmp/database
      - demo-db:/data/db
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' localhost:27017 --quiet
      start_interval: 1s
      start_period: 10s

secrets:
  database_password:
    file: secrets/app_database_password

volumes:
  letsencrypt:
  demo-db:
