# ================================== BUILDER ===================================
ARG  PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION} AS build

# Environments to reduce size of docker image
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONFAULTHANDLER=true
ENV PYTHONUNBUFFERED=true
ENV PYTHONHASHSEED=random
ENV PIP_NO_CACHE_DIR=true
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV PIP_DEFAULT_TIMEOUT=100

# Install system updates and tools
RUN apt-get update 
RUN python -m pip install --upgrade pip

# Add workdir and user non root user
WORKDIR /srv
RUN useradd -m sid

# Copy and install testing requirements
COPY --chown=sid:sid requirements-test.txt /srv
RUN python -m pip install -r requirements-test.txt

# Copy and install client package
COPY --chown=sid:sid client /srv/client
RUN python -m pip install ./client

# Copy tests and change to non root user
COPY --chown=sid:sid tests /srv/tests
COPY --chown=sid:sid pytest.ini /srv
RUN chown -R sid:sid /srv
USER sid

# Define entrypoint and default command
ENTRYPOINT [ "python", "-m", "pytest" ]
# EGI OP does not support authentication in parallel
# CMD [ "-n=auto", "tests" ]
CMD [ "tests" ]
