# Routing -----------------------------------------------------------
[http.routers.frontend]
  rule        = "Host(`{{ env `DOMAIN_NAME` }}`)"
  service     = "frontend"
  entryPoints = ["web", "websecure"]
[http.routers.frontend.tls]
  certresolver = "resolver0"
[http.routers.swagger-ui]
  rule        = "Host(`{{ env `DOMAIN_NAME` }}`) && PathPrefix(`/api`)"
  middlewares = ["cors", "replace-api", "redirect-api"]
  service     = "swagger-ui"
  entryPoints = ["web", "websecure"]
[http.routers.swagger-ui.tls]
  certresolver = "resolver0"
[http.routers.backend-latest]
  rule        = "Host(`{{ env `DOMAIN_NAME` }}`) && PathPrefix(`/api/latest`)"
  middlewares = ["cors", "replace-api", "redirect-api", "replace-lts"]
  service     = "backend-latest"
  entryPoints = ["web", "websecure"]
[http.routers.backend-latest.tls]
  certresolver = "resolver0"
[http.routers.backend-v1]
  rule        = "Host(`{{ env `DOMAIN_NAME` }}`) && PathPrefix(`/api/v1`)"
  middlewares = ["cors", "replace-api", "redirect-api", "replace-v1"]
  service     = "backend-v1"
  entryPoints = ["web", "websecure"]
[http.routers.backend-v1.tls]
  certresolver = "resolver0"

# Middlewares -------------------------------------------------------
[http.middlewares.cors.headers]
  accessControlAllowMethods    = "GET,OPTIONS,PUT,POST,PATCH,DELETE"
  accessControlAllowOriginList = "{{ env `CORS_ORIGINS` }}"
  accessControlAllowHeaders    = "Authorization,Content-Type,Accept"
  accessControlExposeHeaders   = "*"
  accessControlMaxAge          = "100"
  addVaryHeader                = true
[http.middlewares.replace-api.replacePathRegex]
  regex       = "^/api/(.*)"
  replacement = "/$1"
[http.middlewares.redirect-api.redirectRegex]
  regex       = "^(.*)/api$$"
  replacement = "$1/api/"
  permanent   = true
[http.middlewares.replace-lts.replacePathRegex]
  regex       = "^/latest/(.*)"
  replacement = "/$1"
[http.middlewares.replace-v1.replacePathRegex]
  regex       = "^/v1/(.*)"
  replacement = "/$1"

# Services ----------------------------------------------------------
[http.services.frontend.loadBalancer]
[[http.services.frontend.loadBalancer.servers]]
  url = "http://frontend:80"
[http.services.swagger-ui.loadBalancer]
[[http.services.swagger-ui.loadBalancer.servers]]
  url = "http://swagger-ui:8080"
[http.services.backend-latest.loadBalancer]
[[http.services.backend-latest.loadBalancer.servers]]
  url = "http://backend-latest:5000"
[http.services.backend-v1.loadBalancer]
[[http.services.backend-v1.loadBalancer.servers]]
  url = "http://backend-v1:5000"
