# http routing section
[http]
  [http.routers]
    # Define a connection between requests and frontend service
    [http.routers.frontend]
      rule = "Host(`{{ env `DOMAIN_NAME` }}`)"
      # If the rule matches, applies the middleware
      middlewares = ["cors"]
      # If the rule matches, forward to the whoami service (declared below)
      service = "frontend"
      # Define the entrypoints to listen to
      entryPoints = ["websecure"]
      # Define the tls configuration to use
      [http.routers.frontend.tls]
        certresolver = "resolver0"
    # Define a connection between requests and backend service
    [http.routers.backend]
      rule = "Host(`{{ env `DOMAIN_NAME` }}`) && PathPrefix(`/api`)"
      # If the rule matches, applies the middleware
      middlewares = ["cors", "strip-prefix"]
      # If the rule matches, forward to the whoami service (declared below)
      service = "backend"
      # Define the entrypoints to listen to
      entryPoints = ["websecure"]
      # Define the tls configuration to use
      [http.routers.backend.tls]
        certresolver = "resolver0"

[http.middlewares]
  # Define the cors middleware
  [http.middlewares.cors.headers]
    accesscontrolallowmethods = "GET,OPTIONS,PUT,POST,PATCH,DELETE"
  # Define the strip prefix middleware
  [http.middlewares.strip-prefix.stripprefix]
    prefixes = ["/api"]

[http.services]
  # Service to reach frontend 
  [http.services.frontend.loadBalancer]
    [[http.services.frontend.loadBalancer.servers]]
      url = "http://frontend:8501"
  # Service to reach backend
  [http.services.backend.loadBalancer]
    [[http.services.backend.loadBalancer.servers]]
      url = "http://backend:5000"
